package okano.dev.android.derdiedas.data.exercise

import android.content.res.AssetManager
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import okano.dev.android.derdiedas.data.exercise.model.ContentJson
import okano.dev.android.derdiedas.data.exercise.model.ExerciseSet
import okano.dev.android.derdiedas.data.exercise.model.ExerciseSetSummary

/**
 * Where exercise content comes from.
 *
 * Suspending rather than Flow-based: bundled content is fixed for the process lifetime, so
 * a Flow would advertise a change notification that never arrives. A remote source later
 * implements this same interface, or wraps it as a caching decorator, without touching
 * any call site.
 *
 * Mirrors the NounRepository / LocalNounRepository split already in the codebase.
 */
interface ExerciseRepository {
    suspend fun getIndex(): List<ExerciseSetSummary>
    suspend fun getSet(id: String): ExerciseSet
}

/**
 * Reads the JSON generated by `tools/sync-exercises` out of the APK's assets.
 *
 * The index is ~50 KB and each set is at most 48 KB, so parsing on demand is cheap enough
 * that caching content in Room would cost a schema migration for no gain. Only the most
 * recently opened set is held: a session touches exactly one.
 */
class AssetExerciseRepository(
    private val assets: AssetManager,
    private val io: CoroutineDispatcher = Dispatchers.IO,
) : ExerciseRepository {

    private val lock = Mutex()
    private var index: List<ExerciseSetSummary>? = null
    private var cachedSet: ExerciseSet? = null

    override suspend fun getIndex(): List<ExerciseSetSummary> = lock.withLock {
        index ?: withContext(io) {
            ContentJson.parseIndex(read("$ROOT/index.json")).sets
        }.also { index = it }
    }

    override suspend fun getSet(id: String): ExerciseSet = lock.withLock {
        cachedSet?.takeIf { it.id == id } ?: withContext(io) {
            ContentJson.parseSet(read("$ROOT/sets/$id.json"))
        }.also { cachedSet = it }
    }

    private fun read(path: String): String =
        assets.open(path).bufferedReader().use { it.readText() }

    private companion object {
        const val ROOT = "exercises"
    }
}
